// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOL84S_gTGYmL2_GQAmWODcREEuukdoLM',
    appId: '1:179267485570:web:f90347e8bdafdf0101599b',
    messagingSenderId: '179267485570',
    projectId: 'starshare-5e9d8',
    authDomain: 'starshare-5e9d8.firebaseapp.com',
    storageBucket: 'starshare-5e9d8.firebasestorage.app',
    measurementId: 'G-J33NCK7G06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR1gcg2ir_no7_kl0em4h5KR0eW2pvN5s',
    appId: '1:179267485570:android:c407e89c7feb230b01599b',
    messagingSenderId: '179267485570',
    projectId: 'starshare-5e9d8',
    storageBucket: 'starshare-5e9d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0Gq_cTS38tOsUJAN5bY86PChadHzfM44',
    appId: '1:179267485570:ios:e65ac4ebcac6d45a01599b',
    messagingSenderId: '179267485570',
    projectId: 'starshare-5e9d8',
    storageBucket: 'starshare-5e9d8.firebasestorage.app',
    iosBundleId: 'com.example.starshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0Gq_cTS38tOsUJAN5bY86PChadHzfM44',
    appId: '1:179267485570:ios:e65ac4ebcac6d45a01599b',
    messagingSenderId: '179267485570',
    projectId: 'starshare-5e9d8',
    storageBucket: 'starshare-5e9d8.firebasestorage.app',
    iosBundleId: 'com.example.starshare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOL84S_gTGYmL2_GQAmWODcREEuukdoLM',
    appId: '1:179267485570:web:9e3a73c905d963c301599b',
    messagingSenderId: '179267485570',
    projectId: 'starshare-5e9d8',
    authDomain: 'starshare-5e9d8.firebaseapp.com',
    storageBucket: 'starshare-5e9d8.firebasestorage.app',
    measurementId: 'G-PYHCNY3KCK',
  );
}
